create table users (
    username varchar(50) not null primary key,
    password varchar(250) not null,
    enabled boolean not null
);

create table authorities (
    username varchar(50) not null,
    authority varchar(50) not null,
    foreign key (username) references users (username)
);

create table persistent_logins (
    username varchar(64) not null,
    series varchar(64) primary key,
    token varchar(64) not null,
    last_used timestamp not null
);

create table shift (
  id int GENERATED BY DEFAULT AS IDENTITY(START WITH 2002),
  username varchar(50) not null,
  shiftType varchar(50) not null,
  shiftDate date not null,
  primary key (id),
  foreign key (username) references users (username)
);

create table swap (
  id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1001),
  shiftId int not null,
  alternateShiftDate date not null,
  alternateShiftType varchar(50) not null,
  status varchar(50) not null,
  relatedSwapId int,
  primary key (id),
  foreign key (shiftId) references shift (id),
  foreign key (relatedSwapId) references swap(id)
);
